server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: ${app.server.url}:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true